id: I11B8958C
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T14:34:39+00:00'
last_modified: '2022-06-08T09:04:12.327414+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN4336
  title: ཐར་པའི་གྲུ་གཟིངས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '0154':
      image_group_id: I3CN4586
      title: ''
      total_pages: 180
      order: 1
      base_file: 0154.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
