id: P009163
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-19 19:26:02.384363
source_metadata:
  id: bdr:W3CN4336
  title: ཐར་པའི་གྲུ་གཟིངས།
  author: ''
  volumes:
    ef4ae557560542c7b86325fd14ded273:
      image_group_id: I3CN4586
      title: ''
      volume_number: 1
      total_pages: 180
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
